steps:
  - name: 'python:3.11'
    id: Install dependencies and run tests
    entrypoint: bash
    args:
      - -c
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        pytest

  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker image
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/user-management-api:$SHORT_SHA'
      - .

  - name: 'gcr.io/cloud-builders/docker'
    id: Push Docker image
    args:
      - push
      - 'gcr.io/$PROJECT_ID/user-management-api:$SHORT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy to Cloud Run
    entrypoint: gcloud
    args:
      - run
      - deploy
      - user-management-api
      - --image=gcr.io/$PROJECT_ID/user-management-api:$SHORT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
images:
  - 'gcr.io/$PROJECT_ID/user-management-api:$SHORT_SHA'
